production:

  # AWS access key (required)
  access_key_id:

  # AWS secret key (required)
  secret_access_key:

  # Bucket name (required)
  bucket:

  # Identifier for the region in which the bucket was created (required)
  region:

  # Override the S3 Endpoint for non-AWS S3 storages (e.g. Wasabi or DigitalOcean Spaces)
  # endpoint: "https://s3.eu-central-1.wasabisys.com"

  # Folder name inside bucket where uploaded files should be stored (e.g. 'attachments')
  # The default behavior is to store data in the bucket's root directory
  # attachments_folder:

  # Folder where attachment thumbnails are stored
  # thumbnails_folder: thumbnails/

  # set this to a number of ms to use presigned urls instead of public URLs
  # presigned_url_expiry: 3600

development:
  # Copy configuration from `production` if desired

test:
  # Copy configuration from `production` if desired
